# This file contains the list of repositories including their unique short name
# (like a namespace) and the base URL to their location.
#
# Every repo listed here MUST have a corresponding entry in the repos.yaml at
# the root of this source repository with the exception of the Helm hosted ones.
sync:
  repos:
    # Helm hosted repositories
    - name: stable
      url: https://kubernetes-charts.storage.googleapis.com
    - name: incubator
      url: https://kubernetes-charts-incubator.storage.googleapis.com
    - name: jfrog
      url: https://charts.jfrog.io
    - name: rimusz
      url: https://charts.rimusz.net
    - name: buildkite
      url: https://buildkite.github.io/charts
    - name: keel
      url: https://charts.keel.sh
    - name: appscode
      url: https://charts.appscode.com/stable/
    - name: gitlab
      url: https://charts.gitlab.io/
    - name: bitnami
      url: https://charts.bitnami.com
    - name: weave-flux
      url: https://weaveworks.github.io/flux/
    - name: jetstack
      url: https://charts.jetstack.io
    - name: ibm-charts
      url: https://raw.githubusercontent.com/IBM/charts/master/repo/stable/
    - name: kanister
      url: https://charts.kanister.io/
    - name: flagger
      url: https://flagger.app
    - name: zammad
      url: https://zammad.github.io
    - name: agones
      url: https://agones.dev/chart/stable
    - name: banzaicloud-stable
      url: http://kubernetes-charts.banzaicloud.com/branch/master
    - name: kiwigrid
      url: https://kiwigrid.github.io
    - name: elastic
      url: https://helm.elastic.co
    - name: hephy
      url: https://charts.teamhephy.com
