name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install yq
      run: |
        curl -fsSL -o yq https://github.com/mikefarah/yq/releases/download/3.1.1/yq_linux_amd64
        chmod +x yq
        sudo mv yq /usr/local/bin/yq

    - name: Validate repository index
      run: yq v repos.yaml
