name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install yq
      run: |
        curl -fsSL -o yq https://github.com/mikefarah/yq/releases/download/3.1.2/yq_linux_amd64
        chmod +x yq
        sudo mv yq /usr/local/bin/yq

    - name: Validate repos metadata
      run: yq v repos.yaml

    - name: Validate monocular repo configuration
      run: yq v config/repo-values.yaml

    - name: Validate monocular hub values
      run: yq v config/helm-hub-values.yaml
